#*********************************************************************************************************************
# default properties of this micro-services
#*********************************************************************************************************************
# include properties set in separate profiles
spring:
  profiles:
    include:
    - db

# netty-server config, see class S1NettyServerProperties
s1.netty-server:
  port: 8888

---
spring.profiles: test
#*********************************************************************************************************************
# (Unit)test profile
#*********************************************************************************************************************
#Do not actually start Netty Server, befause of using EmbeddedChannel
s1.netty-server:
    actually-started: false
