spring:
  datasource:
    driver-class-name: 
    url: 
    username: 
    password: 
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    database: 20
    password: ''
    port: 6379
    #timeout: 0